spring.application.name=borrowing_management_system

# ===== Database Connection (Supabase PostgreSQL — ใช้ Session Pooler) =====
spring.datasource.url=jdbc:postgresql://postgres.zyymichoggnuycvrfhgi:[YOUR-PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zyymichoggnuycvrfhgi
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

server.port=8080

logging.level.org.hibernate.SQL=debug